import os

import yaml

from src.api.llm_apis import send_request
from src.planning.example_library_manager import get_examples
from src.planning.grammar_rules_manager import get_grammar_rules
from src.planning.vocabulary_set_manager import get_all_vocabulary_set
from src.utils import replace_slot


def planning(user_input):
    '''
    This function is the main entry point for the planning module. 
    It takes the user input and returns the plan generated by LLM.

    Args:
        user_input : the message string from the user

    Returns:
        list: the plan generated by LLM. A list of json objects.
    '''
    
    # read yaml file
    config_path = os.environ.get("CONFIG_PATH")
    config = yaml.load(open(config_path, "r"), Loader=yaml.FullLoader)
    
    # load the system prompt
    system_prompt = config["planning_settings"]["system_prompt"]
    
    # load the user prompt
    user_prompt = config["planning_settings"]["user_prompt"]
    
    # how many seed examples to select from the example library
    number_of_selected_seed_examples = config["planning_settings"]["examples"]["number_of_selected_seed_examples"]
    # how many categories of examples are stored in the example library
    number_of_example_categories = config["planning_settings"]["examples"]["number_of_example_categories"]
    # calculate the number of examples to select from each category
    number_of_selected_seed_examples_per_category = (number_of_selected_seed_examples + number_of_example_categories - 1) // number_of_example_categories
    
    # get the examples from the example library and put them in the message list
    messages = get_examples(
        user_input,
        number_of_selected_seed_examples,
        number_of_selected_seed_examples_per_category
    )
    
    # get the vocabulary set
    vocabulary_set = get_all_vocabulary_set()
    
    # get the grammar rules
    grammar_rules = get_grammar_rules()
    
    # replace the slot in the system prompt
    system_prompt = replace_slot(
        system_prompt,
        {
            "vocabulary_set": vocabulary_set,
            "grammar_rules": grammar_rules
        }
    )
    
    # replace the slot in the user prompt
    user_prompt = replace_slot(
        user_prompt,
        {
            "user_input": user_input,
        }
    )
    
    # insert the system prompt at the beginning of the message list
    messages.insert(0, {
        "role": "system",
        "content": system_prompt
    })
    # append the user prompt at the end of the message list
    messages.append({
        "role": "user",
        "content": user_prompt
    })
    
    return send_request(messages)
